x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

name: aztec-prover
services:
  prover-node:
    image: aztecprotocol/aztec:latest
    restart: always
    <<: *logging
    entrypoint: >-
      node
      --no-warnings
      /usr/src/yarn-project/aztec/dest/bin/index.js
      start
      --prover-node
      --archiver
      --network testnet
    depends_on:
      prover-broker:
        condition: service_started
        required: true
    environment:
      ARCHIVER_BATCH_SIZE: 3
      DATA_DIRECTORY: /var/lib/data
      ETHEREUM_HOSTS: ${EL_NODE}
      L1_CONSENSUS_HOST_URLS: ${CL_NODE}
      LOG_LEVEL: ${LOG_LEVEL}
      PROVER_BROKER_HOST: http://prover-broker:8080
      PROVER_PUBLISHER_PRIVATE_KEY: ${AZTEC_PROVER_PUBLISHER_PRIVATE_KEY}
      P2P_IP: ${P2P_IP}
      P2P_PORT: ${P2P_PORT}
      AZTEC_PORT: ${AZTEC_PORT}
    ports:
      - ${AZTEC_PORT:-8080}:${AZTEC_PORT:-8080}
      - ${P2P_PORT:-40400}:${P2P_PORT:-40400}
      - ${P2P_PORT:-40400}:${P2P_PORT:-40400}/udp
    volumes:
      - aztec-prover-node-data:/var/lib/data
    networks:
      default:
        aliases:
          - aztec-prover-node
          # This allows multiple Eth Docker stacks all connected to the same bridge network
          - ${AZTEC_PROVER_NODE_ALIAS:-default-aztec-prover-node}

  prover-broker:
    image: aztecprotocol/aztec:latest
    <<: *logging
    restart: always
    entrypoint: >-
      node
      --no-warnings
      /usr/src/yarn-project/aztec/dest/bin/index.js
      start
      --prover-broker
      --network testnet
    environment:
      DATA_DIRECTORY: /var/lib/data
      ETHEREUM_HOSTS: ${EL_NODE}
      P2P_IP: ${P2P_IP}
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - aztec-prover-broker-data:/var/lib/data
    networks:
      default:
        aliases:
          - aztec-prover-broker
          # This allows multiple Eth Docker stacks all connected to the same bridge network
          - ${AZTEC_PROVER_BROKER_ALIAS:-default-aztec-prover-broker}

  prover-agent:
    image: aztecprotocol/aztec:latest
    <<: *logging
    entrypoint: >-
      node
      --no-warnings
      /usr/src/yarn-project/aztec/dest/bin/index.js
      start
      --prover-agent
      --network testnet
    environment:
      PROVER_AGENT_COUNT: ${PROVER_AGENT_COUNT:-3}
      PROVER_AGENT_POLL_INTERVAL_MS: ${PROVER_AGENT_POLL_INTERVAL_MS:-10000}
      PROVER_BROKER_HOST: http://prover-broker:8080
      PROVER_ID: ${AZTEC_PROVER_PUBLISHER_ADDRESS}
    pull_policy: always
    restart: always
    networks:
      default:
        aliases:
          - aztec-prover-agent
          # This allows multiple Eth Docker stacks all connected to the same bridge network
          - ${AZTEC_PROVER_AGENT_ALIAS:-default-aztec-prover-agent}

volumes:
  aztec-prover-node-data:
  aztec-prover-broker-data:

networks:
  default:
    enable_ipv6: ${IPV6:-false}
